### PCA

In [1]:
# example of pca for dimensionality reduction
from sklearn.datasets import make_classification
from sklearn.decomposition import PCA

import pandas as pd

In [2]:
path = './feature_selection/credit_cards_dataset.csv'
data = pd.read_csv(path)

In [3]:
data = data.rename(columns={'default.payment.next.month':'DEFAULT_NEXT_MONTH'})

In [4]:
data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT_NEXT_MONTH
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [5]:
y = 'DEFAULT_NEXT_MONTH'
X = [name for name in data.columns if name not in [y, 'ID']]

In [7]:
X=data[X]
y=data[y]

In [8]:
# define the transform
trans = PCA(n_components=10)

# transform the data
X_dim = trans.fit_transform(X)

# summarize data after the transform
print(X_dim[:5, :])

[[-1.66488191e+05 -7.55381537e+04 -4.72952106e+02 -1.38240596e+02
   3.56372601e+02 -2.28581767e+01 -8.61737802e+02  7.90130839e+01
   1.89499608e+02  7.14585844e+02]
 [-1.14226977e+05  9.78067125e+03  2.73444748e+03 -1.56719589e+03
  -4.05071033e+03  6.96602606e+02 -1.51605853e+03  1.26172075e+03
  -6.26282074e+02  4.83598389e+02]
 [-9.84323622e+04 -3.34713873e+04 -2.67846979e+03 -5.10226236e+03
   3.36117708e+03  1.77028488e+02 -6.98694432e+03  1.61205566e+03
  -2.28383642e+03  4.59992560e+03]
 [-7.12306759e+04 -9.52242731e+04 -1.00477170e+04  4.42022296e+03
  -6.37932441e+02  6.19288636e+03  2.36798886e+03  8.37225566e+02
   5.47526631e+02 -1.81557704e+03]
 [-1.14834618e+05 -6.87291852e+04  2.46049481e+04  3.42572904e+04
   8.19783787e+03  4.66873052e+03 -1.18380075e+04  2.72267243e+03
   7.67872253e+03 -6.25666837e+02]]

In [10]:
trans.components_

array([[ 4.91590659e-01, -3.52873014e-08, -3.67290605e-07,
        -1.92469255e-07,  5.56879962e-06,  3.42455214e-07,
         5.68458344e-07,  5.81779941e-07,  6.64584131e-07,
         7.59373260e-07,  8.36871693e-07,  3.88453549e-01,
         3.81356126e-01,  3.72179448e-01,  3.46397504e-01,
         3.22920046e-01,  3.08577267e-01,  2.65676097e-02,
         3.12865310e-02,  2.68185282e-02,  2.21681253e-02,
         2.22044122e-02,  2.48098976e-02],
       [ 8.69022684e-01,  1.76100266e-07, -1.49972284e-06,
        -4.01516316e-07,  8.31332276e-06, -3.80340392e-06,
        -4.62245984e-06, -4.49819779e-06, -4.25959745e-06,
        -4.03177492e-06, -3.98438769e-06, -2.21364316e-01,
        -2.26375798e-01, -2.16534865e-01, -1.94048190e-01,
        -1.76775713e-01, -1.67365250e-01,  5.71625946e-03,
         1.07848222e-02,  1.09685628e-02,  1.03644900e-02,
         1.16931055e-02,  1.53341329e-02],
       [-2.05851404e-02,  3.25238862e-07, -9.72317123e-07,
         7.48257046e-08, -4.13008761e-06, -4.13991968e-07,
        -5.80197703e-07,  5.15515967e-07,  2.10394474e-06,
         3.46127254e-06,  4.45758941e-06, -5.48940631e-01,
        -3.90898860e-01, -4.81697495e-02,  2.60994961e-01,
         4.28102618e-01,  4.83716733e-01,  3.75164975e-02,
         1.59992636e-01,  1.35139321e-01,  9.43991722e-02,
         5.59371797e-02, -2.09321301e-02],
       [-1.84215272e-02, -2.50246977e-08,  2.07190425e-07,
         9.56502175e-08, -2.62035454e-07, -2.62698853e-06,
        -2.67162343e-06, -1.78826370e-06,  2.23719439e-07,
        -8.79366807e-07, -2.24119194e-06, -2.04991534e-01,
        -3.76811676e-02,  5.53401621e-01,  7.92081173e-02,
        -2.00075643e-01, -3.08436830e-01,  1.93664700e-01,
         6.73215329e-01,  2.83788520e-02, -4.02798094e-02,
         1.37315604e-02,  1.23236167e-01],
       [-4.41260367e-02, -3.65041378e-07,  4.52789146e-07,
         6.62098449e-07, -4.90314231e-06, -3.37366196e-06,
        -2.04175493e-06, -3.63085023e-06, -4.42973488e-06,
        -4.18996787e-06, -2.06036311e-06,  3.16878110e-01,
         1.15221251e-02, -2.47861859e-01, -3.67459889e-01,
        -1.57205091e-02,  2.26529259e-01,  2.02709465e-01,
         3.37195286e-01,  3.11083925e-01,  4.36362570e-01,
         3.54931190e-01,  2.85534669e-01],
       [ 1.68691440e-02,  2.03890892e-07,  9.21248690e-08,
        -2.86914843e-07,  1.53998673e-06,  2.18545402e-06,
         2.11500804e-06,  9.97886223e-07,  2.45811207e-06,
        -9.11259120e-07,  7.22386401e-07,  3.32116526e-03,
        -8.10910348e-02,  2.95722868e-01, -4.73493646e-01,
        -7.82441955e-02,  3.91850823e-01, -2.28522066e-01,
         1.08311987e-01, -5.66249624e-01,  2.06567387e-02,
         2.08682745e-01, -3.05358036e-01],
       [-1.12504557e-03,  1.69333795e-07, -6.35800420e-07,
         1.66419252e-07, -1.49380144e-06, -1.79613679e-06,
        -2.62682523e-06,  3.64050999e-06,  8.50650600e-07,
        -8.14233008e-07,  1.03740167e-07, -4.56247729e-01,
         5.26901560e-01,  2.88599668e-02, -1.78524204e-01,
        -1.37943164e-02,  7.73071865e-02,  6.11500634e-01,
        -2.54845653e-01, -1.52989955e-01,  8.51042149e-02,
         6.10279018e-02,  4.57014844e-02],
       [ 1.02718443e-03,  1.81628073e-07, -4.36128786e-08,
        -4.00444317e-07, -2.04510234e-06,  7.88912394e-07,
         6.91577553e-07,  1.35315524e-07,  1.26280291e-06,
        -6.78300120e-07,  3.16562212e-06,  6.88218482e-03,
        -6.55559966e-02,  8.11783835e-02, -2.27804313e-01,
         4.80149740e-01, -2.62952006e-01, -8.19640722e-02,
        -4.77606865e-03, -3.08010607e-01,  4.48171237e-01,
        -4.81743905e-01,  3.20835821e-01],
       [ 9.45640569e-03, -1.31692772e-07,  1.70115204e-07,
        -3.01168309e-07,  7.00452140e-06, -8.30518224e-07,
        -2.07425832e-06, -1.91828163e-06, -2.73916929e-06,
        -1.92198804e-06,  7.36777986e-09,  7.03525751e-02,
         9.92556058e-02, -1.08061305e-01, -9.73680721e-02,
         1.26373631e-01, -1.05358483e-01,  1.70931238e-01,
         2.26416185e-01,  2.27992923e-01,  2.27145844e-01,
        -3.07345771e-01, -8.11394920e-01],
       [ 3.75482915e-03,  1.22095813e-07, -3.03121409e-07,
        -2.37176304e-08, -1.57035819e-07,  2.31296714e-06,
         1.22394680e-06,  3.87719178e-07,  2.39767128e-06,
         4.29680733e-06,  3.81371559e-06,  1.72473551e-01,
         8.08497439e-03, -3.36378186e-01, -1.37021722e-01,
         1.00785083e-01,  2.36964978e-01,  2.79155580e-01,
         3.58024480e-01, -2.01308294e-01, -5.90802567e-01,
        -3.92966167e-01,  1.47762176e-01]])